name: github-release-workflow.yml
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches: [$default-branch]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      run: actions/checkout@v5
      
    - name: Setup dotnet
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'

    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      uses: softprops/action-gh-release@v1
      
      
