name: Move issues
on:
  issues:
    types:
      - opened
      - labeled
      - closed
jobs:
  move_to_project_board:
    runs-on: ubuntu-latest
    steps:
      - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
        if: github.event.action == 'opened'
        with:
          action-token: "${{ secrets.GITHUB_TOKEN }}"
          project-url: "https://github.com/orgs/ITU-BDSA2025-GROUP14/projects/1"
          column-name: "Todo"
          label-name: "triage"
      
      - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
        if: github.event.action == 'labeled' && github.event.label.name == 'in-progress'
        with:
          action-token: "${{ secrets.GITHUB_TOKEN }}"
          project-url: "https://github.com/orgs/ITU-BDSA2025-GROUP14/projects/1"
          column-name: "In Progress"
          label-name: "in-progress"
      
      - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
        if: github.event.action == 'closed'
        with:
          action-token: "${{ secrets.GITHUB_TOKEN }}"
          project-url: "https://github.com/orgs/ITU-BDSA2025-GROUP14/projects/1"
          column-name: "Done"
          label-name: "triage"