name: Move issues
on:
  issues:
    types:
      - opened
      - labeled
      - closed
jobs:
  move_to_project_board:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      repository-projects: write
    steps:
      - name: Wait for labels
        run: sleep 5
        if: github.event.action == 'opened'
        
      - run: |
          # Check if issue has triage label
          if gh issue view ${{ github.event.issue.number }} --json labels --jq '.labels[].name' | grep -q "triage"; then
            gh project item-add 1 --owner ITU-BDSA2025-GROUP14 --url ${{ github.event.issue.html_url }}
            echo "Added issue to project board"
          else
            echo "Issue does not have triage label yet"
          fi
        if: github.event.action == 'opened'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
      
      - run: gh project item-add 1 --owner ITU-BDSA2025-GROUP14 --url ${{ github.event.issue.html_url }}
        if: github.event.action == 'labeled' && github.event.label.name == 'triage'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - run: gh issue edit ${{ github.event.issue.number }} --add-label "done"
        if: github.event.action == 'closed'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}