name: Move issues
on:
  issues:
    types:
      - labeled
      - closed
jobs:
  move_to_project_board:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      repository-projects: write
    steps:
      - run: gh project item-add 1 --owner ITU-BDSA2025-GROUP14 --url ${{ github.event.issue.html_url }}
        if: github.event.action == 'labeled' && github.event.label.name == 'triage'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - run: gh issue edit ${{ github.event.issue.number }} --add-label "done"
        if: github.event.action == 'closed'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}